services:
  db:
    image: postgres:15
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mipassword
      POSTGRES_DB: users_db
    ports:
      - "5441:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: